### ISSUE TITLE
Avoid to fill up the feed

### ISSUE THREAD

**Issue by laurentkempe** [glconti/jira-bot-teams#2]
I would like to get the message in my teams channel but that the message does not appear on the feed

**Comment by glconti** [comment]
Good idea, based on the doc, we could use this property https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/activity-feed#rest-api-sample

**Comment by glconti** [comment]
It was a good idea, but a MS employee confirmed [on Stackoverflow](https://stackoverflow.com/questions/49983130/ms-teams-dont-show-notification-of-specific-message-in-the-activity-feed) that it's not doable at the moment, so I have to close this one 😭
